image: docker:latest
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  GIT_SSL_NO_VERIFY: "1"
#services:
#  - docker:dind
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository
stages:
  - build
  - deploy

# Dev 分支CI
build:devel:
  stage: build
  before_script:
    - export COMMIT_TIME=$(date +%Y%m%d)
    - export ISO_8601=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    - export JIB_FROM_IMAGE=oci.ketanyun.cn/open/openjdk:8-jdk
    - export JIB_TO_IMAGE=oci.ketanyun.cn/product/images/iga:latest
  script:
    - "mvn package  $MAVEN_CLI_OPTS -DJIB_TO_IMAGE=${JIB_TO_IMAGE} -Dcommit.time=${COMMIT_TIME}   -Djib.to.auth.username=${OCI_JIB_TO_USER} -Djib.to.auth.password=${OCI_JIB_TO_PASSWORD} -DJIB_FROM_IMAGE=${JIB_FROM_IMAGE}  -DISO_8601=${ISO_8601}"
  only:
    - dev
  artifacts:
    paths:
      - target/*.war
  image: maven:3-jdk-8

# Dev 分支CD, 自动发布只devel环境
deploy:devel:
  image: bitnami/kubectl:1.17.4
  stage: deploy
  script:
#    - sed -i   "s/iga/iga-devel/g" k8s-service.yaml
#    - kubectl apply -f k8s-service.yaml
#    - 'sed -i   "s/name\: iga/name\: iga-devel/g" k8s-deploy.yaml'
#    - 'sed -i   "s/app\: iga/app\: iga-devel/g" k8s-deploy.yaml'
#    - kubectl apply -f k8s-deploy.yaml
#    - kubectl -nketanyun rollout restart sts iga-devel
    - kubectl -n devel apply -f k8s-service.yaml
    - kubectl -n devel apply -f k8s-deploy.yaml
    - kubectl -n devel rollout restart sts iga
  # disable artifacts downloading from previous steps
  dependencies: [ ]
  environment:
    name: dev
    url: http://devel.ketanyun.cn/iga
  only:
    - dev
  #when: manual

# dev 分支CD, 手动发布到Cloud环境
deploy:prod:
  image: bitnami/kubectl:1.17.4
  stage: deploy
  before_script:
    - export COMMIT_TIME=$(date +%Y%m%d)
  script:
    #  - kubectl -n ketanyun apply -f k8s-service.yaml
    #  - kubectl -n ketanyun apply -f k8s-deploy.yaml
     - kubectl -n ketanyun  set image sts/iga iga="oci.ketanyun.cn/product/images/iga:${COMMIT_TIME}"
  # disable artifacts downloading from previous steps
  dependencies: [ ]
  environment:
    name: prod
    url: https://cloud.ketanyun.cn/iga
  only:
    - master
  when: manual

# Master 分支CI，并自动产生一个以当前日期为版本号的镜像
build:prod:
  stage: build
  before_script:
    - export COMMIT_TIME=$(date +%Y%m%d)
    - export ISO_8601=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    - export JIB_FROM_IMAGE=oci.ketanyun.cn/open/openjdk:8-jre-alpine
    - export JIB_TO_IMAGE=oci.ketanyun.cn/product/images/iga:20230831
  script:
    - "mvn package  $MAVEN_CLI_OPTS -DJIB_TO_IMAGE=${JIB_TO_IMAGE} -Dcommit.time=${COMMIT_TIME}   -Djib.to.auth.username=${OCI_JIB_TO_USER} -Djib.to.auth.password=${OCI_JIB_TO_PASSWORD} -DJIB_FROM_IMAGE=${JIB_FROM_IMAGE} -Djib.from.auth.username='' -Djib.from.auth.password='' -DISO_8601=${ISO_8601}"
  only:
    - master
  artifacts:
    paths:
      - target/*.war
  image: maven:3-jdk-8




