apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: iga
  name: iga
#  namespace: ketanyun
spec:
  serviceName: iga
  replicas: 1
  selector:
    matchLabels:
      app: iga
  template:
    metadata:
      labels:
        app: iga
    spec:
      containers:
      - name: iga
        image: docker.qtgl.com.cn/product/iga:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: qapp-secret-iga
          - configMapRef:
              name: qservice-discovery
        env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: IGA_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: iga_datasource_url
          - name: IGA_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: iga_datasource_username
          - name: IGA_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: iga_datasource_password
          - name: SSO_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_datasource_url
          - name: SSO_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_datasource_username
          - name: SSO_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_datasource_password
          - name: SSO_API_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_api_datasource_password
          - name: SSO_API_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_api_datasource_url
          - name: SSO_API_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_api_datasource_username
          - name: SSO_API_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_api_datasource_password
          - name: SSO_API_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: sso_api_datasource_password
#          - name: SSO_URL
#            valueFrom:
#              secretKeyRef:
#                name: iga-secret
#                key: sso_url
#          - name: APP_CLIENT
#            valueFrom:
#              secretKeyRef:
#                name: iga-secret
#                key: app_client
#          - name: APP_SECRET
#            valueFrom:
#              secretKeyRef:
#                name: iga-secret
#                key: app_secret
#          - name: BUS_URL
#            valueFrom:
#              secretKeyRef:
#                name: iga-secret
#                key: bus_url
          - name: TASK_CRON
            valueFrom:
              secretKeyRef:
                name: iga-secret
                key: task_cron

        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: gitlab-registry-qtgl


