spring:
  datasource:
    iga:
      url: jdbc:mysql://localhost:3306/iga
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    sso:
      url: jdbc:mysql://localhost:3306/sso
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    sso-api:
      url:
      username:
      password:
      type:

graphql:
  url: /graphql






