spring:
  datasource:
    iga:
      url: ${IGA_DATASOURCE_URL}
      username: ${IGA_DATASOURCE_USERNAME}
      password: ${IGA_DATASOURCE_PASSWORD}
      type: com.alibaba.druid.pool.DruidDataSource
      max-wait: 1200000
    sso:
      url: ${SSO_DATASOURCE_URL}
      username: ${SSO_DATASOURCE_USERNAME}
      password: ${SSO_DATASOURCE_PASSWORD}
      type: com.alibaba.druid.pool.DruidDataSource
      max-wait: 1200000
      api:
        url: ${SSO_API_DATASOURCE_URL}
        username: ${SSO_API_DATASOURCE_USERNAME}
        password: ${SSO_API_DATASOURCE_PASSWORD}
        type: com.alibaba.druid.pool.DruidDataSource
        max-wait: 1200000

graphql:
  url: /graphql


# sso地址
sso:
  token:
    url: ${OAUTH_TOKEN_URL}
  authorize:
    url: ${OAUTH_AUTHORIZE_URL}

#app
app:
  client: ${OAUTH_CLIENT_ID}
  secret: ${OAUTH_CLIENT_SECRET}
  scope: data,introspect,acl


# 数据网关地址
bus:
  url: ${BUS_URL}

server:
  servlet:
    context-path: /iga
  origin: ${SERVICE_ORIGIN}

file:
  url: ${FILE_URL}


task:
  cron: ${TASK_CRON}



iga:
  hostname: ${HOSTNAME}


logging:
  file:
    name: iga.log