spring:
  datasource:
    iga:
      url: ${IGA_DATASOURCE_URL}
      username: ${IGA_DATASOURCE_USERNAME}
      password: ${IGA_DATASOURCE_PASSWORD}
      type: com.alibaba.druid.pool.DruidDataSource
    sso:
      url: ${SSO_DATASOURCE_URL}
      username: ${SSO_DATASOURCE_USERNAME}
      password: ${SSO_DATASOURCE_PASSWORD}
      type: com.alibaba.druid.pool.DruidDataSource
      api:
        url: ${SSO_API_DATASOURCE_URL}
        username: ${SSO_API_DATASOURCE_USERNAME}
        password: ${SSO_API_DATASOURCE_PASSWORD}
        type: com.alibaba.druid.pool.DruidDataSource

graphql:
  url: /graphql


# sso地址
sso:
  url: ${SSO_URL}

#app
app:
  client: ${APP_CLIENT}
  secret: ${APP_SECRET}
  scope: data,introspect


# 数据网关地址
bus:
  url: ${BUS_URL}

server:
  servlet:
    context-path: /iga


iga:
  hostname: ${HOSTNAME}