spring:
  datasource:
    iga:
      url: jdbc:mysql://localhost:3306/iga?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    sso:
      url: jdbc:mysql://localhost:3306/sso
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    sso-api:
      url:
      username:
      password:
      type:

graphql:
  url: /graphql


# sso地址
sso:
  url: https://cloud.ketanyun.cn/sso
  #http://devel.ketanyun.cn/sso/

#app
app:
  client: 2jlgzrK3qNKfHvCTNhNm
  secret: 1937EC3B79E34A37C1202FD6AD6D4ABF13B9196437EAB95B
  scope: data,introspect


# 数据网关地址
bus:
  url: /bus

server:
  servlet:
    context-path: /iga