spring:
  datasource:
    iga:
      url: jdbc:mysql://localhost:3306/iga?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    sso:
      url: jdbc:mysql://localhost:3306/sso
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    sso-api:
      url:
      username:
      password:
      type:

graphql:
  url: /graphql


# sso地址
sso:
  url: https://cloud.ketanyun.cn/sso


# 数据网关地址
bus:
  url:

server:
  servlet:
    context-path: /iga
#