apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qiga.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qiga
    # singular name to be used as an alias on the CLI and for display
    singular: qiga
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QIga
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - upstream
              upstream:
                type: object
                required:
                  - appCode
                  - appName
                  - tenant
                  - appClientId
                  - deptTreeType
                properties:
                  # 应用代码
                  appCode:
                    type: string
                  # 应用名称
                  appName:
                    type: string
                  # 数据前缀代码 HR
                  dataCode:
                    type: string
                  # 代表色
                  color:
                    type: string
                   # 租户
                  tenant:
                    type: string
                  # 应用ClientId
                  appClientId:
                    type: string
                  #需要授权的组织机构类型(01:单位类型组织机构,02:党务类型组织机构,03:学术类型组织机构,04:议事协调类型组织机构)
                  deptTreeType:
                    type: string
                    enum: 01